# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SonJasper
tagline:          'A Jekyll theme'
description:      'A Developer from Somewhere'
url:              http://eugene2candy.github.com
baseurl:          /

author:
  name:           'SonJasper'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
disqus: sonjasper
